### ISSUE TITLE
Object-Driven Example 'System.ArgumentException'

### ISSUE THREAD

**Issue by Toemsel** [Toemsel/Network#23]
1. Start the example client and server
2. Choose the "UnSecure" server option
3. Choose the "Object driven example" client option

1/5 times an exception occurs.

```
Exception has occurred: CLR/System.ArgumentException
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll: 'Must specify valid information for parsing in the string.'
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Network.Converter.PacketConverter.DeserialiseObjectFromReader(Object obj, PropertyInfo propertyInfo, BinaryReader binaryReader) in /home/lord/Dev/Network/Network/Network/Converter/PacketConverter.cs:line 358
```

![alt text](https://i.ibb.co/H2rd9ZV/Screenshot-from-2019-04-11-01-22-00.png)

Interesting is, that the variable "bla" is empty in 1/5 times. Either there is an issue while serializing or deserializing.

**Comment by Toemsel** [comment]
Fixed with https://github.com/Toemsel/Network/commit/c654505eb7bf8c18ded4b30d068e160910e8e96b
